name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Compile Java Code
      run: javac -d bin -cp 'lib/*' $(find src -name '*.java')

    - name: Run Tests
      run: java -cp 'bin:lib/*' org.junit.runner.JUnitCore $(find src/test -name '*Test.java' | sed 's|^src/test/||' | sed 's|.java$||' | sed 's|/|.|g')

    - name: Generate Code Coverage
      run: |
        java -javaagent:lib/jacocoagent.jar=destfile=jacoco.exec -cp 'bin:lib/*' org.junit.runner.JUnitCore $(find src/test -name '*Test.java' | sed 's|^src/test/||' | sed 's|.java$||' | sed 's|/|.|g')
        java -jar lib/jacococli.jar report jacoco.exec --classfiles bin --sourcefiles src --html report

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./jacoco.exec
        fail_ci_if_error: true
        verbose: true
